### PR TITLE
fix(download): remove version from remote filename

### LINKED ISSUE #1: Cannot install Stylua v0.13.0
**Describe the bug**

Stylua v0.13.0 removes the version from the release file names.

**Steps to reproduce**

`asdf install stylua 0.13.0`

**Expected behavior**

Stylua 0.13.0 is installed.

**Additional context**

Release: https://github.com/JohnnyMorganz/StyLua/releases/tag/v0.13.0
Issue: https://github.com/JohnnyMorganz/StyLua/issues/343#issuecomment-1085137654

### PR DESCRIPTION
**Pull request by sid-maddy**
Fixes #1

### CODE REVIEW

**Comment by sid-maddy** [comment]
Test run
```
❯ asdf plugin test stylua https://github.com/sid-maddy/asdf-stylua.git --asdf-plugin-gitref main 'stylua --version'
Updating stylua to main
Already on 'main'
Your branch is up to date with 'origin/main'.
* Downloading stylua release 0.13.0...
Archive:  /tmp/asdf.ivhs/downloads/stylua/0.13.0/stylua-0.13.0.zip
  inflating: /tmp/asdf.ivhs/downloads/stylua/0.13.0/bin/stylua
stylua 0.13.0 installation was successful!
stylua 0.13.0
```

**Comment by jc00ke** [comment]
Thanks! Can you still install older versions with this change? I assume not so I'll have to think of how I want to handle that.

**Comment by sid-maddy** [comment]
It does!
```
❯ asdf plugin test stylua https://github.com/sid-maddy/asdf-stylua.git --asdf-plugin-gitref main --asdf-tool-version 0.12.0 'stylua --version'
Updating stylua to main
Already on 'main'
Your branch is up to date with 'origin/main'.
* Downloading stylua release 0.12.0...
Archive:  /var/folders/hg/vhlmrcwx26gg1pwlzpxbx23c0000gq/T/asdf.XXXX.HM0On7EH/downloads/stylua/0.12.0/stylua-0.12.0.zip
  inflating: /var/folders/hg/vhlmrcwx26gg1pwlzpxbx23c0000gq/T/asdf.XXXX.HM0On7EH/downloads/stylua/0.12.0/bin/stylua
stylua 0.12.0 installation was successful!
stylua 0.12.0
```

**Comment by jc00ke** [comment]
> Thanks! Can you still install older versions with this change? I assume not so I'll have to think of how I want to handle that.

I should have looked closer at the PR... that's what I get for reviewing code on my phone while still in bed :laughing:

**Comment by jc00ke** [comment]
Thank you!

**Pull request merged**
